// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderManagementApp.Data;

#nullable disable

namespace OrderManagementApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("OrderManagementApp.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderDate = new DateTime(2024, 12, 17, 20, 7, 58, 316, DateTimeKind.Local).AddTicks(235),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            OrderDate = new DateTime(2024, 12, 16, 20, 7, 58, 317, DateTimeKind.Local).AddTicks(5167),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            OrderDate = new DateTime(2024, 12, 15, 20, 7, 58, 317, DateTimeKind.Local).AddTicks(5189),
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            OrderDate = new DateTime(2024, 12, 14, 20, 7, 58, 317, DateTimeKind.Local).AddTicks(5191),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            OrderDate = new DateTime(2024, 12, 13, 20, 7, 58, 317, DateTimeKind.Local).AddTicks(5192),
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            OrderDate = new DateTime(2024, 12, 12, 20, 7, 58, 317, DateTimeKind.Local).AddTicks(5198),
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            OrderDate = new DateTime(2024, 12, 11, 20, 7, 58, 317, DateTimeKind.Local).AddTicks(5199),
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            OrderDate = new DateTime(2024, 12, 10, 20, 7, 58, 317, DateTimeKind.Local).AddTicks(5200),
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            OrderDate = new DateTime(2024, 12, 9, 20, 7, 58, 317, DateTimeKind.Local).AddTicks(5201),
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            OrderDate = new DateTime(2024, 12, 8, 20, 7, 58, 317, DateTimeKind.Local).AddTicks(5202),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("OrderManagementApp.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails", (string)null);

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 12m
                        },
                        new
                        {
                            OrderId = 1,
                            ProductId = 4,
                            Quantity = 2,
                            UnitPrice = 13m
                        },
                        new
                        {
                            OrderId = 1,
                            ProductId = 5,
                            Quantity = 3,
                            UnitPrice = 14m
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 13m
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = 5,
                            Quantity = 2,
                            UnitPrice = 14m
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = 6,
                            Quantity = 3,
                            UnitPrice = 15m
                        },
                        new
                        {
                            OrderId = 3,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 14m
                        },
                        new
                        {
                            OrderId = 3,
                            ProductId = 6,
                            Quantity = 2,
                            UnitPrice = 15m
                        },
                        new
                        {
                            OrderId = 3,
                            ProductId = 7,
                            Quantity = 3,
                            UnitPrice = 16m
                        },
                        new
                        {
                            OrderId = 4,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 15m
                        },
                        new
                        {
                            OrderId = 4,
                            ProductId = 7,
                            Quantity = 2,
                            UnitPrice = 16m
                        },
                        new
                        {
                            OrderId = 4,
                            ProductId = 8,
                            Quantity = 3,
                            UnitPrice = 17m
                        },
                        new
                        {
                            OrderId = 5,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 16m
                        },
                        new
                        {
                            OrderId = 5,
                            ProductId = 8,
                            Quantity = 2,
                            UnitPrice = 17m
                        },
                        new
                        {
                            OrderId = 5,
                            ProductId = 9,
                            Quantity = 3,
                            UnitPrice = 18m
                        },
                        new
                        {
                            OrderId = 6,
                            ProductId = 8,
                            Quantity = 1,
                            UnitPrice = 17m
                        },
                        new
                        {
                            OrderId = 6,
                            ProductId = 9,
                            Quantity = 2,
                            UnitPrice = 18m
                        },
                        new
                        {
                            OrderId = 6,
                            ProductId = 10,
                            Quantity = 3,
                            UnitPrice = 19m
                        },
                        new
                        {
                            OrderId = 7,
                            ProductId = 9,
                            Quantity = 1,
                            UnitPrice = 18m
                        },
                        new
                        {
                            OrderId = 7,
                            ProductId = 10,
                            Quantity = 2,
                            UnitPrice = 19m
                        },
                        new
                        {
                            OrderId = 7,
                            ProductId = 11,
                            Quantity = 3,
                            UnitPrice = 20m
                        },
                        new
                        {
                            OrderId = 8,
                            ProductId = 10,
                            Quantity = 1,
                            UnitPrice = 19m
                        },
                        new
                        {
                            OrderId = 8,
                            ProductId = 11,
                            Quantity = 2,
                            UnitPrice = 20m
                        },
                        new
                        {
                            OrderId = 8,
                            ProductId = 12,
                            Quantity = 3,
                            UnitPrice = 21m
                        },
                        new
                        {
                            OrderId = 9,
                            ProductId = 11,
                            Quantity = 1,
                            UnitPrice = 20m
                        },
                        new
                        {
                            OrderId = 9,
                            ProductId = 12,
                            Quantity = 2,
                            UnitPrice = 21m
                        },
                        new
                        {
                            OrderId = 9,
                            ProductId = 13,
                            Quantity = 3,
                            UnitPrice = 22m
                        },
                        new
                        {
                            OrderId = 10,
                            ProductId = 12,
                            Quantity = 1,
                            UnitPrice = 21m
                        },
                        new
                        {
                            OrderId = 10,
                            ProductId = 13,
                            Quantity = 2,
                            UnitPrice = 22m
                        },
                        new
                        {
                            OrderId = 10,
                            ProductId = 14,
                            Quantity = 3,
                            UnitPrice = 23m
                        });
                });

            modelBuilder.Entity("OrderManagementApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Product 1",
                            Price = 11m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Product 2",
                            Price = 12m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Product 3",
                            Price = 13m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Product 4",
                            Price = 14m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Product 5",
                            Price = 15m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Product 6",
                            Price = 16m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Product 7",
                            Price = 17m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Product 8",
                            Price = 18m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Product 9",
                            Price = 19m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Product 10",
                            Price = 20m
                        },
                        new
                        {
                            Id = 11,
                            Name = "Product 11",
                            Price = 21m
                        },
                        new
                        {
                            Id = 12,
                            Name = "Product 12",
                            Price = 22m
                        },
                        new
                        {
                            Id = 13,
                            Name = "Product 13",
                            Price = 23m
                        },
                        new
                        {
                            Id = 14,
                            Name = "Product 14",
                            Price = 24m
                        },
                        new
                        {
                            Id = 15,
                            Name = "Product 15",
                            Price = 25m
                        },
                        new
                        {
                            Id = 16,
                            Name = "Product 16",
                            Price = 26m
                        },
                        new
                        {
                            Id = 17,
                            Name = "Product 17",
                            Price = 27m
                        },
                        new
                        {
                            Id = 18,
                            Name = "Product 18",
                            Price = 28m
                        },
                        new
                        {
                            Id = 19,
                            Name = "Product 19",
                            Price = 29m
                        },
                        new
                        {
                            Id = 20,
                            Name = "Product 20",
                            Price = 30m
                        },
                        new
                        {
                            Id = 21,
                            Name = "Product 21",
                            Price = 31m
                        },
                        new
                        {
                            Id = 22,
                            Name = "Product 22",
                            Price = 32m
                        },
                        new
                        {
                            Id = 23,
                            Name = "Product 23",
                            Price = 33m
                        },
                        new
                        {
                            Id = 24,
                            Name = "Product 24",
                            Price = 34m
                        },
                        new
                        {
                            Id = 25,
                            Name = "Product 25",
                            Price = 35m
                        },
                        new
                        {
                            Id = 26,
                            Name = "Product 26",
                            Price = 36m
                        },
                        new
                        {
                            Id = 27,
                            Name = "Product 27",
                            Price = 37m
                        },
                        new
                        {
                            Id = 28,
                            Name = "Product 28",
                            Price = 38m
                        },
                        new
                        {
                            Id = 29,
                            Name = "Product 29",
                            Price = 39m
                        },
                        new
                        {
                            Id = 30,
                            Name = "Product 30",
                            Price = 40m
                        });
                });

            modelBuilder.Entity("OrderManagementApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            Name = "Bob"
                        });
                });

            modelBuilder.Entity("OrderManagementApp.Models.Order", b =>
                {
                    b.HasOne("OrderManagementApp.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrderManagementApp.Models.OrderDetail", b =>
                {
                    b.HasOne("OrderManagementApp.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderManagementApp.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderManagementApp.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("OrderManagementApp.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("OrderManagementApp.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
